mysql:
  image: mysql:latest
  environment:
    - MYSQL_DATABASE=django
    - MYSQL_ROOT_PASSWORD=mysql
    - MYSQL_CHARSET=utf8mb4
  ports:
    - "3306:3306"

web:
  build: .
  command: python ./manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - mysql:mysql
